# 1. 텐서

텐서(Tensor)는 파이토치의 기본 단위이며 GPU 연산을 가능하게 한다. 또한 Numpy의 배열과 유사하여 손쉽게 다룰 수 있다.

## 1.1 텐서 만들기

In [1]:
# 라이브러리 불러오기
import torch # Pytorch를 사용하기 위한 기본 라이브러리다.
import numpy as np # Numpy를 사용하기 위한 기본 라이브러리다.

In [2]:
# 빈 텐서 생성
x = torch.empty(5,4) # 5x4 행렬 생성
print(x) # 초기화되지 않은 행렬인 경우 해당 시점에 할당된 메모리에 존재하던 값들이 초기값으로 나타난다.

tensor([[8.9082e-39, 5.9694e-39, 8.9082e-39, 1.0194e-38],
        [9.1837e-39, 4.6837e-39, 9.9184e-39, 9.0000e-39],
        [1.0561e-38, 1.0653e-38, 4.1327e-39, 8.9082e-39],
        [9.8265e-39, 9.4592e-39, 1.0561e-38, 1.0653e-38],
        [1.0469e-38, 9.5510e-39, 1.0378e-38, 8.9082e-39]])


In [3]:
torch.ones(3,3) # 3x3 일 행렬

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.zeros(2) # 2행 영 벡터

tensor([0., 0.])

In [5]:
torch.rand(5,6) # 5,6 랜덤 행렬

tensor([[0.8251, 0.0037, 0.0890, 0.6943, 0.8849, 0.8096],
        [0.7177, 0.5448, 0.6631, 0.3262, 0.9155, 0.0641],
        [0.2821, 0.2364, 0.3055, 0.6840, 0.5307, 0.3584],
        [0.0600, 0.9688, 0.1669, 0.8024, 0.5998, 0.7152],
        [0.1721, 0.7122, 0.9531, 0.9306, 0.9715, 0.7723]])

## 1.2 리스트, 넘파이 배열을 텐서로 만들기

In [6]:
l = [13,4] # 리스트 생성
r = np.array([4,56,7]) # 넘파이 배열 생성

In [7]:
torch.tensor(l) # 리스트를 텐서로 쉽게 변환할 수 있다.

tensor([13,  4])

In [8]:
torch.tensor(r) #넘파이 배열을 텐서로 쉽게 변환할 수 있다.

tensor([ 4, 56,  7], dtype=torch.int32)

## 1.3 텐서의 크기와 타입 확인하기

In [10]:
x.size()[1] # .size()는 텐서의 크기를 확인할 수 있으며 매우 자주 사용된다.

4

In [11]:
type(x) # type은 Python에서 사용되는 모든 것들을 종류를 보여준다. 

torch.Tensor

In [12]:
x = torch.rand(2,2) # 2x2 랜덤 행렬
y = torch.rand(2,2) # 2x2 랜덤 행렬
print(x)
print(y)

tensor([[0.1642, 0.2998],
        [0.3750, 0.5736]])
tensor([[0.8880, 0.3242],
        [0.3036, 0.5495]])


In [13]:
x+y # 두 텐서의 합

tensor([[1.0522, 0.6239],
        [0.6786, 1.1232]])

In [14]:
torch.add(x,y) # 두 텐서의 합의 또 다른 표현

tensor([[1.0522, 0.6239],
        [0.6786, 1.1232]])

In [15]:
y.add(x) # 두 텐서의 합의 또 다른 표현이지만 이는 y에 x를 더한다는 의미다.

tensor([[1.0522, 0.6239],
        [0.6786, 1.1232]])

In [16]:
print("원래 y: ", y)
y.add_(x)
print("y=y+x: ",y)

# y.add_는 y에 x를 더한 값을 y에 대체한다.(inplace 방식)

원래 y:  tensor([[0.8880, 0.3242],
        [0.3036, 0.5495]])
y=y+x:  tensor([[1.0522, 0.6239],
        [0.6786, 1.1232]])


## 1.5 텐서의 크기 변환하기

In [17]:
x = torch.rand(8,8) # 8x8 랜덤 행렬
print(x.size())

torch.Size([8, 8])


In [18]:
a = x.view(64) # 크기를 바꿔주는 view 8x8 -> 64
print(a.size())

torch.Size([64])


In [19]:
b = x.view(-1,4,4) # -1은 원래 크기가 되게 하는 값 8x8 -> -1x4x4 즉, 4x4x4이다.
print(b.size()) 

# 따라서 -1은 원래 크기가 되게 하는 값이 자동으로 지정되기 때문에 한 번만 사용할 수 있다. 
# 예를 들어 x.view(-1,-1,4)와 같은 선언은 오류가 난다.

torch.Size([4, 4, 4])


## 1.6 텐서에서 넘파이로 만들기

In [20]:
x = torch.rand(8,8)
y = x.numpy() # .numpy()로 매우 간단하게 넘파이 배열로 만들 수 있다.
print(y)

[[0.16849405 0.4578299  0.20527267 0.83358485 0.03465074 0.95311666
  0.333744   0.6643823 ]
 [0.2764541  0.5954518  0.2692147  0.5256448  0.49700135 0.15283537
  0.25660837 0.87977654]
 [0.17412502 0.43413007 0.8013221  0.9842426  0.7975203  0.49262416
  0.7998201  0.27717888]
 [0.04440504 0.10322917 0.8336891  0.557894   0.41402733 0.28345048
  0.37513465 0.02339894]
 [0.13993204 0.02375448 0.1918416  0.44558907 0.9457377  0.9412522
  0.11698174 0.35610598]
 [0.46314758 0.7695324  0.7026266  0.32708603 0.26566315 0.60321814
  0.76493835 0.42806917]
 [0.54800755 0.16355497 0.22192067 0.7033036  0.4017262  0.93673825
  0.7935792  0.12284344]
 [0.08555049 0.86008245 0.3496492  0.7615522  0.8718193  0.25743347
  0.69223905 0.54483265]]


In [21]:
type(y)

numpy.ndarray

## 1.7 단일 텐서에서 값으로 뽑아내기

In [22]:
x = torch.ones(1)

In [23]:
print(x)
print(x.item()) # .item()은 손실 함숫값과 같이 숫자가 하나인 텐서를 텐서가 아닌 값으로 만들어 준다.

tensor([1.])
1.0
